#!/bin/sh

set -e

case "$1" in
  purge)
    if [ -d /etc/transmission-daemon/settings.json ]; then
      rm -rf /etc/transmission-daemon/*
    fi
  ;;
esac

# Automatically added by dh_installinit/13.1
if [ "$1" = "purge" ] ; then
	update-rc.d transmission-daemon remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'transmission-daemon.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'transmission-daemon.service' >/dev/null || true
		deb-systemd-helper unmask 'transmission-daemon.service' >/dev/null || true
	fi
fi
# End automatically added section

