#!/bin/sh

set -e

test $DEBIAN_SCRIPT_DEBUG && set -v -x

chperms() {
	# chperms <user> <group> <perms> <file>
	if ! OVERRIDE=`dpkg-statoverride --list $4 2>&1`; then
		if [ -e $4 ]; then
			chown $1:$2 $4
			chmod $3 $4
		fi
	fi
}

case "$1" in
  configure)
    if ! getent passwd vpn > /dev/null; then
        adduser --quiet \
                --system \
                --group \
                --disabled-password \
                --home /home/vpn \
                vpn
    fi

    chperms vpn vpn 2775 /usr/local/bin/transmission-daemon
    chperms vpn vpn 2775 /usr/local/bin/transmission-remote
    chperms vpn vpn 2775 /usr/local/bin/transmission-show
    chperms vpn vpn 2775 /usr/local/bin/transmission-edit
    chperms vpn vpn 2775 /usr/local/bin/transmission-create

   # Set permissions on data directory (always do this instead only on creation in case user was changed via dpkg-reconfigure)
#chown -R media:media /home/media/.config/Sonarr


# Set permissions on /usr/lib/sonarr
chown -R vpn:vpn /home/vpn
chown -R vpn:vpn /usr/local/share/transmission
chown -R vpn:vpn /etc/transmission-daemon
  ;;
esac

# Automatically added by dh_systemd_enable/13.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'transmission-daemon.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'transmission-daemon.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'transmission-daemon.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'transmission-daemon.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/13.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/transmission-daemon" ]; then
		update-rc.d transmission-daemon defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d transmission-daemon $_dh_action || exit 1
	fi
fi
# End automatically added section


exit 0;
